---
# Alex Nasca 
# 1/3/2024
# CDT basic infrastructure configuration  Script
- name: Install and configure services with user creation
  hosts: all #run on all hosts specified in inventory file
  become: true  # Run tasks with sudo privileges

  tasks:
    - name: Update APT
      apt:
        update_cache: yes

    - name: Install Apache2 on 192.168.0.10
      apt:
        name: apache2 #installs apache2 using apt 
      when: "'192.168.0.10' in inventory_hostname" #only runs when ip matches in the inventory file 

    - name: Install MySQL on 192.168.0.11
      apt:
        name: mysql-server  #installs sql server (can log in as root with no password by defualt)
      when: "'192.168.0.11' in inventory_hostname"

    - name: Install vsftpd on 192.168.0.12
      apt:
        name: vsftpd #installs an FTP service called vsftpd
      when: "'192.168.0.12' in inventory_hostname"

    - name: Create TestUser1
      user:
        name: TestUser1 #name of new user 
        password: "{{ 'password' | password_hash('sha512') }}" # has to hash password to place into shadow file correctly
        shell: /bin/bash #sets the shell for the user on login 
      ignore_errors: yes  # Ignore errors if the user already exists

    - name: Create TestSudo1
      user:
        name: TestSudo1 #name of new user 
        password: "{{ 'password' | password_hash('sha512') }}" # has to hash password to place into shadow file correctly
        shell: /bin/bash #sets the shell for the user on login 
      ignore_errors: yes  # Ignore errors if the user already exists

    - name: Add TestSudo1 to sudoers group
      user:
        name: TestSudo1  #username set above
        groups: sudo #add to sudo group
        shell: /bin/bash 
      ignore_errors: yes  
